[package]
name = "rust_wren"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
tokio = { version = "1.18.2", features = ["full"] }

[build-dependencies]
bindgen = "0.59.2"
