[package]
name = "wren_sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "lib.rs"

[dependencies]

[build-dependencies]
bindgen = "0.59.2"
which = "4.2.5"
cc = "1.0"
